// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Note;
@class Note_Builder;

@interface NoteProtobufRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Note : PBGeneratedMessage {
@private
  BOOL hasBtAddress_:1;
  BOOL hasMeetingId_:1;
  BOOL hasMessage_:1;
  NSString* btAddress;
  NSString* meetingId;
  NSString* message;
}
- (BOOL) hasBtAddress;
- (BOOL) hasMeetingId;
- (BOOL) hasMessage;
@property (readonly, retain) NSString* btAddress;
@property (readonly, retain) NSString* meetingId;
@property (readonly, retain) NSString* message;

+ (Note*) defaultInstance;
- (Note*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Note_Builder*) builder;
+ (Note_Builder*) builder;
+ (Note_Builder*) builderWithPrototype:(Note*) prototype;

+ (Note*) parseFromData:(NSData*) data;
+ (Note*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Note*) parseFromInputStream:(NSInputStream*) input;
+ (Note*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Note*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Note*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Note_Builder : PBGeneratedMessage_Builder {
@private
  Note* result;
}

- (Note*) defaultInstance;

- (Note_Builder*) clear;
- (Note_Builder*) clone;

- (Note*) build;
- (Note*) buildPartial;

- (Note_Builder*) mergeFrom:(Note*) other;
- (Note_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Note_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBtAddress;
- (NSString*) btAddress;
- (Note_Builder*) setBtAddress:(NSString*) value;
- (Note_Builder*) clearBtAddress;

- (BOOL) hasMeetingId;
- (NSString*) meetingId;
- (Note_Builder*) setMeetingId:(NSString*) value;
- (Note_Builder*) clearMeetingId;

- (BOOL) hasMessage;
- (NSString*) message;
- (Note_Builder*) setMessage:(NSString*) value;
- (Note_Builder*) clearMessage;
@end

