
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: NoteProtobuf.proto
namespace ac.uk.brunel.contextaware
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Note")]
    public partial class Note : global::ProtoBuf.IExtensible
    {
      public Note() {}
      
    private string _btAddress;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"btAddress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string btAddress
    {
      get { return _btAddress; }
      set { _btAddress = value; }
    }

    private string _meetingId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"meetingId", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue("")]
    public string meetingId
    {
      get { return _meetingId; }
      set { _meetingId = value; }
    }

    private string _message = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
}
